//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/ArticleService.Model")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IArticleService")]
    public interface IArticleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetData", ReplyAction="http://tempuri.org/IArticleService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetData", ReplyAction="http://tempuri.org/IArticleService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetArticles", ReplyAction="http://tempuri.org/IArticleService/GetArticlesResponse")]
        ArticleClient.ServiceReference1.Article[] GetArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetArticles", ReplyAction="http://tempuri.org/IArticleService/GetArticlesResponse")]
        System.Threading.Tasks.Task<ArticleClient.ServiceReference1.Article[]> GetArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/CreateBill", ReplyAction="http://tempuri.org/IArticleService/CreateBillResponse")]
        void CreateBill(string billText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/CreateBill", ReplyAction="http://tempuri.org/IArticleService/CreateBillResponse")]
        System.Threading.Tasks.Task CreateBillAsync(string billText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/UpdateArticles", ReplyAction="http://tempuri.org/IArticleService/UpdateArticlesResponse")]
        void UpdateArticles(ArticleClient.ServiceReference1.Article[] articles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/UpdateArticles", ReplyAction="http://tempuri.org/IArticleService/UpdateArticlesResponse")]
        System.Threading.Tasks.Task UpdateArticlesAsync(ArticleClient.ServiceReference1.Article[] articles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticleServiceChannel : ArticleClient.ServiceReference1.IArticleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleServiceClient : System.ServiceModel.ClientBase<ArticleClient.ServiceReference1.IArticleService>, ArticleClient.ServiceReference1.IArticleService {
        
        public ArticleServiceClient() {
        }
        
        public ArticleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ArticleClient.ServiceReference1.Article[] GetArticles() {
            return base.Channel.GetArticles();
        }
        
        public System.Threading.Tasks.Task<ArticleClient.ServiceReference1.Article[]> GetArticlesAsync() {
            return base.Channel.GetArticlesAsync();
        }
        
        public void CreateBill(string billText) {
            base.Channel.CreateBill(billText);
        }
        
        public System.Threading.Tasks.Task CreateBillAsync(string billText) {
            return base.Channel.CreateBillAsync(billText);
        }
        
        public void UpdateArticles(ArticleClient.ServiceReference1.Article[] articles) {
            base.Channel.UpdateArticles(articles);
        }
        
        public System.Threading.Tasks.Task UpdateArticlesAsync(ArticleClient.ServiceReference1.Article[] articles) {
            return base.Channel.UpdateArticlesAsync(articles);
        }
    }
}
